/*
 * Northstar Competition Lab — data-driven frontend.
 *
 * The single source of truth is site-data/site.json, generated by
 * `python -m northstar.cli run-pipeline` from the committed, hash-checked
 * fixtures. This file renders it; it stores no data of its own (the
 * hypothesis registry below is documentation of untested designs).
 */

const $ = (id) => document.getElementById(id);
const escapeHtml = (value) =>
  String(value ?? "").replace(/[&<>"']/g, (char) => ({
    "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;",
  }[char]));

const fmtUnits = (v) =>
  v === null || v === undefined ? "—" :
  (v > 0 ? "+" : "") + Number(v).toFixed(2);
const fmtPct = (v) =>
  v === null || v === undefined ? "—" : (100 * Number(v)).toFixed(1) + "%";
const fmtDate = (iso) => {
  if (!iso) return "—";
  const d = new Date(iso);
  return Number.isNaN(d.getTime()) ? escapeHtml(iso) :
    d.toISOString().slice(0, 16).replace("T", " ");
};

/* ------------------------------------------------------------------ */
/* Untested hypothesis registry (design documentation, no results).   */
/* Status values: "Pilot-tested" entries are linked to a real backtest. */
/* ------------------------------------------------------------------ */
const hypothesisRegistry = [
  { sport: "Football", name: "Elo rating + price discipline", status: "Pilot-tested", data: "Verified pilot fixtures/results · time-stamped odds", test: "Walk-forward 1X2", tested: "elo-edge-v1" },
  { sport: "Football", name: "Market favourite (baseline)", status: "Pilot-tested", data: "Same verified pilot odds", test: "Walk-forward 1X2", tested: "market-favourite-v1" },
  { sport: "Football", name: "Market longshot (baseline probe)", status: "Pilot-tested", data: "Same verified pilot odds", test: "Walk-forward 1X2", tested: "market-longshot-v1" },
  { sport: "Football", name: "Draw-No-Bet decisive form", status: "Pilot-tested", data: "Same verified pilot odds", test: "Walk-forward 2-way", tested: "draw-no-bet-v1" },
  { sport: "Football", name: "Poisson goal totals", description: "Estimate home and away scoring rates from pre-match history and test totals without information published after kick-off.", status: "Ready to source", data: "Verified scores · line-up/time gate · licensed odds", test: "Walk-forward totals" },
  { sport: "Horse Racing", name: "Place probability by field size", description: "Calibrate place probability separately by race type, field size, going, jurisdiction and declared non-runners; define dead heats before testing.", status: "Blocked", data: "Organizer result · runner archive · licensed odds", test: "Jurisdiction-specific" },
  { sport: "Tennis", name: "Surface-adjusted Elo", description: "Use player ratings split by surface and enforce a match-start cutoff before comparing the forecast with the captured price; define retirements.", status: "Blocked", data: "Governing-body/organizer results · licensed odds", test: "Match-level Brier + ROI" },
  { sport: "Golf", name: "Strokes-gained and course fit", description: "Test pre-tournament player form and course-fit features against a dated outright price; define ties and dead heats before running anything.", status: "Blocked", data: "Tour organizer leaderboards · licensed odds", test: "Outright / place" },
  { sport: "American Football", name: "Efficiency differential with injury freshness", description: "Use a dated injury state and explicit regulation/overtime settlement; hold out any input not available before selection.", status: "Blocked", data: "League results · dated injury archive · licensed odds", test: "Spread / total" },
  { sport: "Baseball", name: "Starting pitcher and bullpen split", description: "Test pre-game pitcher, bullpen availability and park effects without leaking post-lineup information.", status: "Blocked", data: "League results · lineups · licensed odds", test: "Moneyline / totals" },
  { sport: "Basketball", name: "Rest and travel-adjusted rating", description: "Separate home advantage, rest days, travel and overtime from team strength; settle regulation and overtime markets explicitly.", status: "Blocked", data: "League results · schedule · licensed odds", test: "Moneyline / spread" },
  { sport: "Cricket", name: "Venue and innings-state model", description: "Model format-specific run rates by venue and innings; handle rain-reduced matches, declarations and abandoned games explicitly.", status: "Blocked", data: "Competition scorecards · format rules · licensed odds", test: "Match / innings markets" },
  { sport: "Cycling", name: "Course-fit performance delta", description: "Separate time trials from mass-start events and use governing-body classifications with a pre-start feature cutoff.", status: "Blocked", data: "Organizer classifications · licensed odds", test: "Outright / placement" },
  { sport: "Darts", name: "Throw rate plus checkout profile", description: "Compare dated player rates while keeping format, leg distance and event rules consistent; walkovers are not losses.", status: "Blocked", data: "Organizer results · format rules · licensed odds", test: "Match / handicap" },
  { sport: "Gaelic Football", name: "Score-difference rating", description: "Keep Gaelic football separate from rugby; model competition, venue and scoring rules with postponed and replayed fixtures explicit.", status: "Blocked", data: "Competition organizer results · licensed odds", test: "Match / handicap" },
  { sport: "Greyhounds", name: "Box/track pace profile", description: "Freeze trap, distance, going, field and non-runner state at selection time; define voids and photo-finish revisions.", status: "Blocked", data: "Track/organizer results · licensed odds", test: "Win / place" },
  { sport: "Handball", name: "Possession and pace split", description: "Separate league and tournament rules, extra time and seven-metre shootouts before any model result is graded.", status: "Blocked", data: "Federation results · licensed odds", test: "Match / total" },
  { sport: "Hurling", name: "Venue-adjusted scoring rate", description: "Use competition-specific scoring and replay rules; do not pool with Gaelic football or association football.", status: "Blocked", data: "Competition organizer results · licensed odds", test: "Match / handicap" },
  { sport: "Ice Hockey", name: "Hockey Elo favourite (no-market pilot)", description: "2-way Elo (final incl. OT/shootout) used as a no-price baseline; predictions only - graded on accuracy/Brier because no permissioned DEL odds path exists.", status: "Pilot-tested", data: "OpenLigaDB DEL pilot fixtures/results (ODbL) · no permissioned odds", test: "Walk-forward 2-way accuracy", tested: "hockey-elo-v1" },
  { sport: "Ice Hockey", name: "Goalie-adjusted expected goals", description: "Estimate shot quality and goalie availability before puck drop; separate regulation, overtime and shootout settlement.", status: "Blocked", data: "Federation/league results · licensed odds", test: "Moneyline / totals" },
  { sport: "Motor Racing", name: "Qualifying-to-finish delta", description: "Use only pre-race information and define retirements, classified finish, penalties, podium and each-way places per series.", status: "Blocked", data: "Series organizer results · licensed odds", test: "Finish / podium" },
  { sport: "Rugby Union", name: "Set-piece and territory rating", description: "Keep union and league separate; model competition rules, extra time and abandoned matches explicitly.", status: "Blocked", data: "Union organizer results · licensed odds", test: "Match / handicap" },
  { sport: "Rugby League", name: "Tackle/territory rating", description: "Do not pool rugby codes; define golden-point, abandoned and handicap rules before backtesting.", status: "Blocked", data: "League organizer results · licensed odds", test: "Match / handicap" },
  { sport: "Snooker", name: "Frame-strength and break profile", description: "Separate match format, walkovers and frame handicaps; freeze ranking and recent-form features before the match.", status: "Blocked", data: "Tour organizer results · licensed odds", test: "Match / frame handicap" },
  { sport: "Volleyball", name: "Set differential rating", description: "Keep best-of format, golden-set rules and walkovers explicit; never treat a missing set as a loss.", status: "Blocked", data: "Federation results · licensed odds", test: "Match / set handicap" },
  { sport: "Boxing", name: "Opponent-adjusted performance", description: "Use event-organizer/commission results and freeze record, weight class and bout rules at selection time; keep MMA separate.", status: "Blocked", data: "Organizer results · licensed odds", test: "Fight winner / method" },
];

let DATA = null;

/* ------------------------------------------------------------------ */

function stateBadge(state) {
  const map = {
    verified: ["green", "verified"],
    review: ["review", "review · demoted"],
    mixed: ["review", "mixed · review"],
    none: ["muted", "no settled bets"],
  };
  const [cls, label] = map[state] || ["muted", state || "—"];
  return `<span class="badge ${cls}">${escapeHtml(label)}</span>`;
}

function renderOverview() {
  const p = DATA.meta.pilot;
  const snaps = DATA.meta.snapshot_count ?? null;
  $("m-events").textContent = p.events ?? "—";
  $("m-agree").textContent = p.dual_source_agreement ?? "—";
  $("m-snapshots").textContent = snaps ?? "—";
  const cov = DATA.coverage || [];
  const verified = cov.filter((c) => c.status === "pilot_verified").length;
  const open = cov.filter((c) => c.status === "results_path_available").length;
  $("m-coverage").textContent = `${cov.length}`;
  $("m-coverage-sub").textContent = `${verified} pilot-verified · ${open} results-path ready`;
  $("pilot-note").textContent =
    (p.note || "") +
    ` Competition: ${p.competition || "—"}, matchdays ${(p.matchdays || []).join("/")}.` +
    (DATA.meta.hockey ? ` Ice hockey pilot: ${DATA.meta.hockey.competition}, ` +
      `matchdays ${(DATA.meta.hockey.matchdays || []).join("/")}, ` +
      `${DATA.meta.hockey.events ?? "—"} events, ` +
      `${DATA.meta.hockey.source_anomalies ?? "—"} flagged source irregularities. ${DATA.meta.hockey.note || ""}` : "");

  // leaderboard preview
  const rows = (DATA.leaderboard || []).slice(0, 5).map((r) => `
    <tr>
      <td>${r.rank}</td>
      <td><strong>${escapeHtml(r.name)}</strong></td>
      <td>${escapeHtml(r.kind)}</td>
      <td>${r.settled_bets}</td>
      <td>${fmtUnits(r.profit_units)}</td>
      <td>${fmtPct(r.roi)}</td>
      <td>${stateBadge(r.verification_state)}</td>
    </tr>`).join("");
  $("overview-leaderboard").innerHTML = rows;

  // predictions preview (first 2)
  const preds = (DATA.predictions || []).slice(0, 2);
  $("overview-predictions").innerHTML = preds.length ? preds.map(predictionCard).join("") :
    `<div class="empty-state compact"><div class="empty-icon">⌁</div><h3>No predictions rendered</h3><p>Predictions require a full model/fair/edge trail; they are refused when evidence is missing.</p></div>`;

  // integrity gates
  const gates = [];
  const openAnoms = DATA.anomalies?.open ?? 0;
  gates.push(okGate(
    p.dual_source_agreement &&
    String(p.dual_source_agreement).split("/")[0] === String(p.dual_source_agreement).split("/")[1],
    "Dual-source result check",
    `${p.dual_source_agreement || "—"} FT results agree (OpenLigaDB × football-data)`));
  gates.push(okGate(openAnoms === 0,
    "Anomaly queue",
    openAnoms === 0 ? "No open anomalies" : `${openAnoms} open anomalies need review`));
  gates.push(okGate(true,
    "Odds timestamps",
    "All snapshots pre-start, window-close inferred (no exact-time claims)"));
  gates.push(okGate(true,
    "Paper-only accounting",
    "No cash, no live execution; 1.0 level-stake units"));
  gates.push(okGate(false,
    "Sample size",
    "27-match pilot: far too small to separate skill from luck",
    "review"));
  $("gate-list").innerHTML = gates.join("");
  const allOk = openAnoms === 0;
  $("gate-badge").className = "status-badge " + (allOk ? "green" : "review");
  $("gate-badge").textContent = allOk ? "pipeline clean" : "review needed";
}

function okGate(ok, title, sub, force) {
  const state = force || (ok ? "ready" : "review");
  return `<li><span class="check ${state === "review" ? "warning-check" : ""}">${state === "review" ? "!" : "✓"}</span>
    <div><strong>${escapeHtml(title)}</strong><small>${escapeHtml(sub)}</small></div>
    <span class="${state} ${state === "review" ? "review-text" : ""}">${state === "review" ? "Review" : "Ready"}</span></li>`;
}

function predictionCard(p) {
  const links = (p.source_links || []).filter(Boolean).map((u) =>
    `<a href="${escapeHtml(u)}" target="_blank" rel="noreferrer">source ↗</a>`).join(" · ");
  return `<article class="tip-card">
    <span class="tip-sport">${escapeHtml(p.strategy || "model")}${p.market ? ` · ${escapeHtml(marketLabel({ market: p.market, sport: "football" }))}` : ""}</span>
    <span class="tip-status">paper</span>
    <h3 class="tip-event">${escapeHtml(p.headline || "—")}</h3>
    <p class="tip-league">kickoff ${fmtDate(p.event_start_utc)} UTC · ${p.odds ? "odds " + p.odds : "no odds"}</p>
    <p style="font-size:13px;line-height:1.55;margin:10px 0">${escapeHtml(p.body || "")}</p>
    <a class="tip-source" href="#">${links || "no external source"}</a>
  </article>`;
}

function renderLeaderboard() {
  const kind = $("leaderboard-kind").value;
  const rows = (DATA.leaderboard || []).filter(
    (r) => kind === "All kinds" || r.kind === kind);
  $("leaderboard-body").innerHTML = rows.map((r) => `
    <tr>
      <td>${r.rank}</td>
      <td><strong>${escapeHtml(r.name)}</strong><br /><small style="opacity:.7">${escapeHtml(r.description || "")}</small></td>
      <td>${r.settled_bets}</td>
      <td>${r.wins} / ${r.losses}</td>
      <td>${r.voids}</td>
      <td><strong>${fmtUnits(r.profit_units)}</strong></td>
      <td>${fmtPct(r.roi)}</td>
      <td>${fmtPct(r.strike_rate)}</td>
      <td>${r.max_drawdown_units === null ? "—" : "−" + Number(r.max_drawdown_units).toFixed(2)}</td>
      <td>${stateBadge(r.verification_state)}</td>
    </tr>`).join("") || emptyRow(10);
  $("leaderboard-count").textContent = rows.length + " entrants";
  $("nav-count-leaderboard").textContent = DATA.leaderboard?.length ?? 0;
}

function emptyRow(cols) {
  return `<tr><td colspan="${cols}"><em>none</em></td></tr>`;
}

function renderTipDesk() {
  const kind = $("tip-kind").value;
  const q = ($("tip-search").value || "").trim().toLowerCase();
  const entrants = {};
  for (const b of DATA.bets.placed || []) {
    (entrants[b.entrant] ??= { bets: [] }).bets.push(b);
  }
  const lb = {};
  for (const e of DATA.leaderboard || []) {
    lb[e.entrant_id] = e;
    // Keep entrants with no settled/imported rows visible: the manually
    // captured OLBG best-tipster profile is analysis context, not a blank
    // cell that disappears from the separate tipster desk.
    (entrants[e.entrant_id] ??= { bets: [] });
  }
  // Entrant registry (includes prediction-only desks like DEL hockey that
  // are intentionally absent from the PnL leaderboard).
  const registry = {};
  for (const e of DATA.entrants || []) {
    registry[e.entrant_id] = e;
    (entrants[e.entrant_id] ??= { bets: [] });
  }
  const desk = [];
  for (const [id, group] of Object.entries(entrants)) {
    const meta = lb[id] || registry[id] ||
      { name: id, kind: "unknown", description: "" };
    if (kind !== "All kinds" && meta.kind !== kind) continue;
    const hay = (id + " " + meta.name + " " +
      group.bets.map((b) => `${b.event} ${b.market} ${b.selection}`).join(" ")).toLowerCase();
    if (q && !hay.includes(q)) continue;
    desk.push({ id, meta, bets: group.bets });
  }
  desk.sort((a, b) => {
    const ra = lb[a.id]?.rank ?? 999, rb = lb[b.id]?.rank ?? 999;
    return ra - rb || a.id.localeCompare(b.id);
  });
  $("tipster-desk").innerHTML = desk.length ? desk.map((g) => `
    <section class="panel" style="margin-bottom:18px">
      <div class="panel-heading">
        <div><p class="eyebrow">${escapeHtml(g.meta.kind || "entrant")}</p>
        <h2>${escapeHtml(g.meta.name || g.id)}</h2></div>
        <span class="badge ${g.meta.verification_state === "verified" ? "green" : g.meta.verification_state === "review" ? "review" : "muted"}">${g.bets.length} tips</span>
      </div>
      ${g.meta.description ? `<p class="panel-copy">${escapeHtml(g.meta.description)}</p>` : ""}
      <div class="source-table-wrap"><table class="source-table"><thead><tr><th>Event</th><th>Market</th><th>Selection</th><th>Odds</th><th>Status</th><th>Result</th></tr></thead><tbody>
      ${g.bets.length ? g.bets.map(tipRow).join("") : '<tr><td colspan="6"><em>No imported selections attached to this profile; displayed statistics remain external benchmark context.</em></td></tr>'}
      </tbody></table></div>
    </section>`).join("") :
    `<div class="empty-state"><div class="empty-icon">⌕</div><h3>No tips match</h3><p>Try a different kind filter or search term.</p></div>`;
}

// Honest display helpers: "unsettleable" needs an explanation in every
// table where it appears, and the internal 3-way market constant reads
// wrongly for a 2-way hockey decision (final includes OT/shootout).
const STATUS_TITLES = {
  unsettleable:
    "prediction-only: no permissioned entry price exists for this sport, " +
    "so the tip can never be settled and is never counted in profit tables",
};
const statusCell = (s) =>
  `<span${STATUS_TITLES[s] ? ` title="${STATUS_TITLES[s]}"` : ""}>${escapeHtml(s)}</span>`;
const marketLabel = (b) => {
  if (b.market === "match_winner_2way")
    return b.sport === "darts" ? "match winner (sets)"
      : "match winner (incl. OT/SO)";
  if (b.sport === "ice_hockey" && b.market === "match_winner_3way")
    return "match winner (incl. OT/SO)";
  if (b.market === "total_goals_over_under_2_5")
    return "total goals O/U 2.5 (90 min)";
  if (b.market === "match_winner_3way") return "1X2 (90 min)";
  return b.market;
};

function tipRow(b) {
  const settled = b.settlement
    ? `${b.settlement.outcome} · ${b.settlement.verification_state}`
    : (b.status === "pending" ? "pending import" : b.status);
  return `<tr>
    <td>${escapeHtml(b.event)}<br /><small style="opacity:.7">${fmtDate(b.event_start_utc)} UTC</small>
      ${b.source_url ? `<br /><a href="${escapeHtml(b.source_url)}" target="_blank" rel="noreferrer">source ↗</a>` : ""}</td>
    <td>${escapeHtml(marketLabel(b))}</td>
    <td><strong>${escapeHtml(b.selection)}</strong></td>
    <td>${b.odds === null ? "—" : b.odds}</td>
    <td>${statusCell(b.status)}</td>
    <td>${escapeHtml(settled)}${b.pnl_units !== null ? `<br /><small>${fmtUnits(b.pnl_units)} u</small>` : ""}</td>
  </tr>`;
}

function renderBets() {
  const sel = $("bets-entrant");
  const current = sel.value;
  const ids = [...new Set((DATA.bets.placed || []).map((b) => b.entrant))];
  sel.innerHTML = `<option>All entrants</option>` +
    ids.map((i) => `<option${i === current ? " selected" : ""}>${escapeHtml(i)}</option>`).join("");
  const pick = (b) => sel.value === "All entrants" || b.entrant === sel.value;
  const placed = (DATA.bets.placed || []).filter(pick)
    .sort((a, b) => String(b.published_at_utc).localeCompare(String(a.published_at_utc)));
  $("placed-bets-body").innerHTML = placed.map((b) => `
    <tr>
      <td>${escapeHtml(b.event)}<br /><small style="opacity:.7">${fmtDate(b.event_start_utc)} UTC</small>
        ${b.source_url ? `<br /><a href="${escapeHtml(b.source_url)}" target="_blank" rel="noreferrer">source ↗</a>` : ""}</td>
      <td>${escapeHtml(b.entrant)}</td>
      <td>${escapeHtml(marketLabel(b))} · <strong>${escapeHtml(b.selection)}</strong></td>
      <td>${b.odds === null ? "—" : b.odds}</td>
      <td>${statusCell(b.status)}</td>
      <td>${b.pnl_units === null ? "—" : fmtUnits(b.pnl_units)}</td>
      <td>${b.settlement ? `${b.settlement.outcome} · ${b.settlement.verification_state}` : "—"}</td>
    </tr>`).join("") || emptyRow(7);
  const upcoming = (DATA.bets.upcoming || []).filter(pick);
  $("upcoming-bets-body").innerHTML = upcoming.map((b) => `
    <tr>
      <td>${escapeHtml(b.event)}</td>
      <td>${fmtDate(b.event_start_utc)}</td>
      <td>${escapeHtml(b.entrant)}</td>
      <td>${escapeHtml(marketLabel(b))} · <strong>${escapeHtml(b.selection)}</strong></td>
      <td>${b.odds === null ? "—" : b.odds}</td>
      <td><small>${escapeHtml(b.notes || "")}</small></td>
    </tr>`).join("") || emptyRow(6);
  $("bets-count").textContent =
    `${DATA.bets.total_placed} placed · ${DATA.bets.total_upcoming} upcoming`;
  $("nav-count-bets").textContent =
    (DATA.bets.total_placed ?? 0) + (DATA.bets.total_upcoming ?? 0);
}

const SPORT_LABELS = { football: "Football", ice_hockey: "Ice Hockey", darts: "Darts" };

function registryList() {
  return (DATA.registry && DATA.registry.hypotheses) || hypothesisRegistry;
}

function renderStrategies() {
  const tested = DATA.backtest || {};
  const n = Object.keys(tested).length;
  const totalBets = Object.values(tested).reduce((s, t) => s + (t.bets || 0), 0);
  const cleanLeaks = Object.values(tested).every(
    (t) => (t.leak_violations || []).length === 0);
  $("strategy-topline").innerHTML = `
    <div class="strategy-stat"><strong>${n}</strong><span>strategies pilot-tested</span></div>
    <div class="strategy-stat"><strong>${totalBets}</strong><span>walk-forward decisions placed</span></div>
    <div class="strategy-stat ${cleanLeaks ? "" : "warning"}"><strong>${cleanLeaks ? "0" : "!"}</strong><span>time-leakage violations</span></div>
    <div class="strategy-stat"><strong>${DATA.forward?.n_awaiting ?? 0}</strong><span>forward calls open (PnL: unavailable)</span></div>`;

  $("backtest-grid").innerHTML = Object.entries(tested).map(([sid, t]) => {
    const hyp = registryList().find((h) => h.tested === sid);
    const sportLabel = SPORT_LABELS[t.sport] || t.sport || "Football";
    let metaHtml;
    if (t.pnl_available === false) {
      const acc = t.accuracy || {};
      const matchdays = Object.entries(acc.by_matchday || {})
        .sort(([a], [b]) => Number(a) - Number(b))
        .map(([md, d]) => `<span class="metric-chip">MD ${md}: ${d.hits}/${d.n} (${fmtPct(d.accuracy)})</span>`)
        .join(" ");
      metaHtml = `
        <span><strong>Predictions</strong> · ${t.predictions} placed · ${acc.n_graded ?? 0} graded · ${t.skipped} skipped</span>
        <span><strong>Accuracy</strong> · ${acc.hits ?? "—"}/${acc.n_graded ?? "—"} = ${fmtPct(acc.accuracy)} · <strong>Mean Brier</strong> · ${acc.mean_brier ?? "—"}</span>
        <span><strong>PnL</strong> · <em>unavailable</em> — no permissioned odds path for this sport (not zero, not a loss)</span>
        ${matchdays ? `<span class="metric-chips">${matchdays}</span>` : ""}`;
    } else {
      const ci = t.profit_ci95
        ? `[${t.profit_ci95.lo.toFixed(2)}, ${t.profit_ci95.hi.toFixed(2)}]` : "—";
      const stats = (t.p_value_raw !== undefined && t.p_value_raw !== null)
        ? `<span><strong>Bootstrap p</strong> · ${t.p_value_raw} → Holm-adjusted <strong>${t.p_value_holm ?? "—"}</strong> (family m=${t.family_size ?? "—"}${t.significant_after_correction ? ", significant" : ", not significant"})</span>`
        : "";
      metaHtml = `
        <span><strong>Bets</strong> · ${t.bets} placed · ${t.settled} settled · ${t.skipped} skipped</span>
        <span><strong>Profit</strong> · ${fmtUnits(t.profit_units)} u (ROI ${fmtPct(t.roi)}, strike ${fmtPct(t.strike_rate)})</span>
        <span><strong>95% CI</strong> · ${ci} u</span>${stats}`;
    }
    return `<article class="strategy-card" data-strategy-status="${escapeHtml(hyp?.status || "Pilot-tested")}">
      <div class="strategy-card-top"><span class="strategy-sport">${escapeHtml(sportLabel)}${t.market ? ` · ${escapeHtml(marketLabel({ market: t.market, sport: t.sport }))}` : ""}</span>
        <span class="strategy-state">${stateBadge(t.verification_state)}</span></div>
      <h3>${escapeHtml(hyp?.name || sid)}</h3>
      <p>${escapeHtml(hyp?.description || sid)}</p>
      <div class="strategy-meta">${metaHtml}
      </div>
      ${t.sample_warning ? `<span class="tip-flag">⚑ ${escapeHtml(t.sample_warning)}</span>` : ""}
    </article>`;
  }).join("");

  $("prediction-grid").innerHTML = (DATA.predictions || []).map(predictionCard).join("") ||
    `<div class="empty-state compact"><div class="empty-icon">⌁</div><h3>No predictions</h3></div>`;

  renderHypotheses("All");
}

function renderHypotheses(filter) {
  $("strategy-grid").innerHTML = registryList()
    .filter((h) => filter === "All" || h.status === filter)
    .map((h) => `<article class="strategy-card" data-strategy-status="${escapeHtml(h.status)}">
      <div class="strategy-card-top"><span class="strategy-sport">${escapeHtml(h.sport)}</span>
        <span class="strategy-state ${h.status === "Blocked" ? "blocked" : h.status === "Pilot-tested" ? "" : "ready"}">${escapeHtml(h.status)}</span></div>
      <h3>${escapeHtml(h.name)}</h3>
      ${h.description ? `<p>${escapeHtml(h.description)}</p>` : ""}
      <div class="strategy-meta"><span><strong>Data gate</strong> · ${escapeHtml(h.data)}</span><span><strong>Test</strong> · ${escapeHtml(h.test)}</span></div>
      ${h.tested ? `<span class="tip-flag" style="color:var(--green, #39c07f)">✓ backtested as ${escapeHtml(h.tested)}</span>` : ""}
    </article>`).join("");
}

const FORWARD_STATE_LABEL = {
  graded: ["green", "graded"],
  awaiting_result: ["ready", "awaiting result"],
  overdue: ["review", "overdue — review queue"],
};

function renderForward() {
  const f = DATA.forward || {};
  const state = f.state || "awaiting_first_capture";
  $("nav-count-forward").textContent = f.n_awaiting ?? 0;
  $("forward-cadence").textContent = f.cadence ||
    "append-only ledger · frozen at capture time";
  const chip = (label, value, warn) =>
    `<div class="strategy-stat${warn ? " warning" : ""}"><strong>${value}</strong><span>${label}</span></div>`;
  $("forward-topline").innerHTML =
    chip("state", state === "live" ? "LIVE" : "awaiting capture") +
    chip("predictions issued", f.n_issued ?? 0) +
    chip("graded", f.n_graded ?? 0) +
    chip("awaiting result", f.n_awaiting ?? 0) +
    chip("overdue", f.n_overdue ?? 0, (f.n_overdue ?? 0) > 0) +
    chip("cutoff violations", (f.leak_violations || []).length,
      (f.leak_violations || []).length > 0);
  if (f.latest_capture_utc) {
    $("forward-topline").innerHTML +=
      `<div class="strategy-stat"><strong>${fmtDate(f.latest_capture_utc)}</strong><span>latest capture (UTC)</span></div>`;
  }

  const rendered = f.rendered || [];
  $("forward-predictions").innerHTML = rendered.length
    ? rendered.map((p) => `
      <article class="tip-card">
        <span class="tip-sport">${escapeHtml(SPORT_LABELS[p.sport] || p.sport || "")} · ${escapeHtml(p.strategy)}</span>
        <span class="tip-status${p.evidence_ok ? "" : " review"}">${p.evidence_ok ? "forward · frozen" : "renderer refused"}</span>
        <h3 class="tip-event">${escapeHtml(p.headline)}</h3>
        <p class="tip-league">${escapeHtml(p.competition || "")} · kickoff ${fmtDate(p.start_utc)} UTC · cutoff ${fmtDate(p.cutoff_utc)} UTC</p>
        <p style="font-size:13px;line-height:1.55;margin:10px 0">${escapeHtml(p.body || "")}</p>
        <span class="tip-source">${(p.source_links || []).filter(Boolean).map((u) => `<a href="${escapeHtml(u)}" target="_blank" rel="noreferrer">evidence ↗</a>`).join(" · ") || "no external source"}</span>
      </article>`).join("")
    : `<div class="empty-state compact"><div class="empty-icon">⏱</div><h3>${state === "live" ? "No upcoming calls inside the issue horizon" : "Awaiting the first current-season capture"}</h3><p>${escapeHtml(f.note || "The CI capture workflow fetches the permitted OpenLigaDB current-season payloads and issues the first frozen predictions into the ledger.")}</p></div>`;

  const gradedRows = (f.graded || []).map((r) => `
    <tr>
      <td>${escapeHtml(r.event)}<br /><small style="opacity:.7">${escapeHtml(r.competition || "")}</small></td>
      <td>${escapeHtml(r.strategy_id)}</td>
      <td><strong>${escapeHtml(r.selection)}</strong></td>
      <td>${escapeHtml(r.result || "")} (${escapeHtml(r.actual || "")})</td>
      <td>${r.hit ? '<span class="source-state green">hit</span>' : '<span class="source-state review">miss</span>'}</td>
      <td>${r.brier ?? "—"}</td>
      <td><small>${fmtDate(r.issued_at_utc)}</small></td>
    </tr>`).join("");
  $("forward-graded-body").innerHTML = gradedRows || emptyRow(7);
  $("forward-graded-count").textContent = `${(f.graded || []).length} graded`;

  const open = [...(f.overdue || []), ...(f.awaiting || [])];
  $("forward-awaiting-body").innerHTML = open.map((r) => {
    const [cls, label] = FORWARD_STATE_LABEL[r.status] || ["muted", r.status];
    return `<tr>
      <td>${escapeHtml(r.event)}<br /><small style="opacity:.7">${escapeHtml(r.competition || "")}
        ${r.source_url ? ` · <a href="${escapeHtml(r.source_url)}" target="_blank" rel="noreferrer">source ↗</a>` : ""}</small></td>
      <td><small>${fmtDate(r.start_utc)}</small></td>
      <td>${escapeHtml(r.strategy_id)}</td>
      <td><strong>${escapeHtml(r.selection)}</strong></td>
      <td><small>${fmtDate(r.cutoff_utc)}</small></td>
      <td><span class="source-state ${cls}"${r.note ? ` title="${escapeHtml(r.note)}"` : ""}>${escapeHtml(label)}</span></td>
    </tr>`;
  }).join("") || emptyRow(6);
  $("forward-awaiting-count").textContent = `${open.length} open`;
}

function renderIntegrity() {
  const anoms = (DATA.anomalies && DATA.anomalies.queue) || [];
  const open = (DATA.anomalies && DATA.anomalies.open) || 0;
  const chip = (label, value, warn) =>
    `<div class="strategy-stat${warn ? " warning" : ""}"><strong>${value}</strong><span>${label}</span></div>`;
  $("integrity-topline").innerHTML =
    chip("open anomalies", open, open > 0) +
    chip("resolved", anoms.filter((a) => a.status === "resolved").length) +
    chip("total flagged", anoms.length) +
    chip("events in store", DATA.meta.event_count ?? 0);
  $("integrity-count").textContent = `${anoms.length} rows`;
  $("anomaly-body").innerHTML = anoms.map((a) => `
    <tr>
      <td><span class="source-state ${a.status === "open" ? "review" : "green"}">${escapeHtml(a.kind)}</span></td>
      <td><code>${escapeHtml(a.entity_type)}:${escapeHtml(a.entity_id.slice(0, 24))}</code></td>
      <td><small>${escapeHtml(a.detail)}</small></td>
      <td>${(a.source_urls || []).filter(Boolean).map((u) => `<a href="${escapeHtml(u)}" target="_blank" rel="noreferrer">↗</a>`).join(" ") || "—"}</td>
      <td>${escapeHtml(a.status)}</td>
      <td><small>${fmtDate(a.detected_at_utc)}</small></td>
    </tr>`).join("") || emptyRow(6);
}

function renderSources() {
  $("source-cards").innerHTML = (DATA.sources || []).map((s) => `
    <section class="panel" style="margin-bottom:18px">
      <div class="panel-heading">
        <div><p class="eyebrow">${escapeHtml(s.source_id)}</p><h2>${escapeHtml(s.display_name)}</h2></div>
        <span class="badge ${s.license_id === "odbl-1.0" ? "green" : s.license_id === "copyright-reserved" ? "review" : "muted"}">${escapeHtml(s.license_id)}</span>
      </div>
      <p class="panel-copy">${escapeHtml(s.license_summary)}</p>
      <div class="strategy-meta">
        <span><strong>Permitted modes</strong> · ${escapeHtml(s.collection_modes.join(", "))}</span>
        <span><strong>Rate limit</strong> · ${escapeHtml(s.rate_limit)}</span>
        <span><strong>Verified</strong> · ${escapeHtml(s.verified_at)}</span>
        ${s.requires_active_entitlement ? `<span><strong>Build state</strong> · licensed entitlement required; inactive in this public build</span>` : ""}
      </div>
      ${(s.caveats || []).length ? `<p class="panel-copy" style="margin-top:10px"><strong>Caveats:</strong> ${s.caveats.map(escapeHtml).join(" · ")}</p>` : ""}
      <p style="margin-top:10px">${(s.evidence_urls || []).map((u) =>
        `<a href="${escapeHtml(u)}" target="_blank" rel="noreferrer" style="margin-right:12px">${escapeHtml(u)} ↗</a>`).join("")}</p>
    </section>`).join("");

  const covStyle = {
    pilot_verified: "green",
    results_pilot: "ready",
    results_path_available: "ready",
    verification_blocked: "blocked",
  };
  const olbgRows = (DATA.coverage || [])
    .filter((c) => c.scope !== "extra").map(covRow);
  const extraRows = (DATA.coverage || [])
    .filter((c) => c.scope === "extra").map(covRow);
  function covRow(c) {
    return `
    <tr>
      <td><strong>${escapeHtml(c.sport)}</strong></td>
      <td>${escapeHtml(c.results_path)}</td>
      <td>${escapeHtml(c.odds_path)}</td>
      <td><span class="source-state ${covStyle[c.status] || ""}">${escapeHtml(c.status)}</span></td>
      <td><small>${escapeHtml(c.note || "")}</small></td>
    </tr>`;
  }
  $("coverage-body").innerHTML = olbgRows +
    (extraRows.length ? `<tr><td colspan="5" style="opacity:.6">Extra candidates (not on the OLBG sport list)</td></tr>` : "") +
    extraRows;

  $("captures-body").innerHTML = (DATA.captures || []).map((c) => `
    <tr>
      <td>${escapeHtml(c.source_id)}</td>
      <td><code>${escapeHtml(c.path)}</code></td>
      <td>${escapeHtml(c.mode)}</td>
      <td><code>${escapeHtml(String(c.sha256).slice(0, 16))}…</code></td>
      <td><small>${escapeHtml(c.note || "")}</small></td>
    </tr>`).join("") || emptyRow(5);
}

function setView(viewName) {
  document.querySelectorAll("[data-view-panel]").forEach((panel) =>
    panel.classList.toggle("active", panel.dataset.viewPanel === viewName));
  document.querySelectorAll(".nav-item[data-view]").forEach((item) =>
    item.classList.toggle("active", item.dataset.view === viewName));
  const active = document.querySelector(`.nav-item[data-view="${viewName}"]`);
  $("page-name").textContent = active
    ? active.textContent.trim().replace(/\s+\d+$/, "")
    : "Overview";
  window.scrollTo({ top: 0, behavior: "smooth" });
}

function init(data) {
  DATA = data;
  $("last-sync").textContent =
    "Static research build · " +
    new Date(data.meta.built_utc).toISOString().slice(0, 10).replace(/-/g, "/");
  $("data-error").hidden = true;
  document.querySelector('[data-view-panel="overview"]').classList.add("active");

  renderOverview();
  renderLeaderboard();
  renderTipDesk();
  renderBets();
  renderStrategies();
  renderForward();
  renderIntegrity();
  renderSources();

  document.querySelectorAll(".nav-item[data-view]").forEach((item) =>
    item.addEventListener("click", () => setView(item.dataset.view)));
  document.querySelectorAll("[data-view-target]").forEach((item) =>
    item.addEventListener("click", () => setView(item.dataset.viewTarget)));
  $("leaderboard-kind").addEventListener("change", renderLeaderboard);
  $("tip-search").addEventListener("input", renderTipDesk);
  $("tip-kind").addEventListener("change", renderTipDesk);
  $("bets-entrant").addEventListener("change", renderBets);
  document.querySelectorAll("[data-strategy-filter]").forEach((button) =>
    button.addEventListener("click", () => {
      document.querySelectorAll("[data-strategy-filter]").forEach((item) =>
        item.classList.toggle("active", item === button));
      renderHypotheses(button.dataset.strategyFilter);
    }));
}

document.addEventListener("DOMContentLoaded", () => {
  fetch("site-data/site.json", { cache: "no-store" })
    .then((res) => {
      if (!res.ok) throw new Error("HTTP " + res.status);
      return res.json();
    })
    .then(init)
    .catch((err) => {
      const box = $("data-error");
      box.hidden = false;
      document.querySelectorAll("[data-view-panel]").forEach((p) =>
        p.classList.remove("active"));
      $("data-error-msg").textContent =
        `site-data/site.json could not be loaded (${err.message}). ` +
        "Run `python -m northstar.cli run-pipeline` to regenerate it, then serve the folder (GitHub Pages does this automatically).";
    });
});
